version: "3"

services: 

  website:
    build: website
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=semanticscience.org,sio.semanticscience.org
    volumes:
      - ./website/html:/var/www/html
      - ./loader:/loader
      - ./website/arc:/lib/arc
      - git-data:/data
    networks:
      - net
    #ports:
    #  - 81:80
      
  virtuoso:
    image: tenforce/virtuoso
    # restart: unless-stopped
    hostname: bio2rdf.org
    environment:
      - DBA_PASSWORD=dba
      - SPARQL_UPDATE=true
      # - DEFAULT_GRAPH=http://bio2rdf.org/
      #- VIRT_SPARQL_MaxQueryCostEstimationTime=100000
      #- VIRT_SPARQL_MaxQueryCostEstimationTime=9000
      #- VIRT_SPARQL_MaxQueryExecutionTime=6000
      - VIRT_PARAMETERS_DirsAllowed=., /import, /usr/local/virtuoso-opensource/share/virtuoso/vad
    volumes:
      - git-data:/usr/local/virtuoso-opensource/var/lib/virtuoso/db/import
      # - C:/data/semanticscience/db:/data
      #- C:/data/semanticscience/sio:/data/sio
      # - ./virtuoso/virtuoso.ini:/data/virtuoso.ini
    networks:
      - net
    ports:
      - 8891:8890

volumes:
  git-data:
                                            
networks:

  net:
    driver: bridge
