version: "3"

services: 

  website:
    build: website
    container_name: semanticscience-website
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=semanticscience.org,sio.semanticscience.org
      - LETSENCRYPT_HOST=semanticscience.org,sio.semanticscience.org
    volumes:
      - ./website/html:/var/www/html
      - ./website/arc:/lib/arc
      - ./loader:/loader
      - /data/semanticscience-data:/data
    networks:
      - net
      
  virtuoso:
    image: tenforce/virtuoso
    container_name: semanticscience-virtuoso
    restart: unless-stopped
    # hostname: bio2rdf.org
    environment:
      - DBA_PASSWORD=dba
      - SPARQL_UPDATE=true
      - VIRT_PARAMETERS_DirsAllowed=., /import, /usr/local/virtuoso-opensource/share/virtuoso/vad
    volumes:
      - /data/semanticscience-data:/usr/local/virtuoso-opensource/var/lib/virtuoso/db/import
    networks:
      - net
                                            
networks:
  net:
    driver: bridge
