version: "3"

services: 

  website:
    build: website
    restart: unless-stopped
    volumes:
      - ./website/html:/var/www/html
      - ./website/arc:/lib/arc
      - ./loader:/loader
      - git-data:/data
    networks:
      - net
    ports:
      - 81:80
      
  virtuoso:
    image: tenforce/virtuoso
    restart: unless-stopped
    hostname: bio2rdf.org
    environment:
      - DBA_PASSWORD=dba
      - SPARQL_UPDATE=true
      - VIRT_PARAMETERS_DirsAllowed=., /import, /usr/local/virtuoso-opensource/share/virtuoso/vad
    volumes:
      - git-data:/usr/local/virtuoso-opensource/var/lib/virtuoso/db/import
    networks:
      - net
    ports:
      - 8890:8890

volumes:
  git-data:
                                            
networks:
  net:
    driver: bridge
